export enum ClientState {
    MAIN_MENU = 'MAIN_MENU',
    CONNECTING = 'CONNECTING',
    SERVER_SELECTION = 'SERVER_SELECTION', 
    WAITING_FOR_MATCH = 'WAITING_FOR_MATCH', 
    IN_MATCH = 'IN_MATCH',
    MATCH_SUMMARY = 'MATCH_SUMMARY',
    SETTINGS = 'SETTINGS',
    ERROR = 'ERROR'

}